version: "3"
services:
    nginx:
      image: nginx:1.23.4
      restart: unless-stopped
      volumes:
        - ./nginx/scraapy-nossl.conf:/etc/nginx/nginx.conf
        - ./dist:/var/www/html
      ports:
        - "80:80"
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
